### PR TITLE
Enhancements

### PR DESCRIPTION
**Pull request by tzneal**
Fixes: #51, #38 and #36

*Description of changes:*

Fix the check for terminal pods.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by mbevc1 — APPROVED** [review]

**Comment by mbevc1** [comment]
Seems like it's updating the Pod graphs now :tada: . Thanks! qq, are those showing Pod binded or running as it seems to update it before Node is in `Ready` state?

**Review by bwagner5 — APPROVED** [review]
LGTM

**Comment by tzneal** [comment]
@mbevc1 It it showing pods that are bound, but not necessarily running yet.

**Comment by mbevc1** [comment]
Cheers :+1: .

**Pull request merged**
