### PR TITLE
Fix spot price

### LINKED ISSUE #63: Spot Pricing Incorrect
It appears that on spot instances the price estimate is using the on-demand price:

```log
ip-10-63-242-25.ec2.internal  cpu    █████████████████████████████████░░  94% (14 pods) c6a.large/$0.076    On-Demand - Ready 
                              memory ███████████████████░░░░░░░░░░░░░░░░  54%                                                 
ip-10-63-247-246.ec2.internal cpu    ████████████████████████████░░░░░░░  79% (13 pods) c6a.large/$0.076    On-Demand - Ready 
                              memory ███████████████████░░░░░░░░░░░░░░░░  54%                                                 
ip-10-63-240-13.ec2.internal  cpu    ███████████████████████████████████  99% (18 pods) c6a.large           -         - Ready 
                              memory ████████████████████████████████░░░  91%                                                 
ip-10-63-243-187.ec2.internal cpu    ███████████████████████████████████ 100% (15 pods) c6a.large           -         - Ready 
                              memory ████████████████████████░░░░░░░░░░░  68%                                                 
ip-10-63-243-63.ec2.internal  cpu    ██████████████████████████████████░  97% (15 pods) c6in.large/$0.113   Spot      - Ready 
                              memory ███████████████████████████████░░░░  89%                                                 
ip-10-63-242-35.ec2.internal  cpu    █████████████████████████████████░░  94% (13 pods) c6i.large/$0.085    Spot      - Ready 
                              memory ██████████████████████░░░░░░░░░░░░░  64%                                                 
ip-10-63-245-172.ec2.internal cpu    ███████████████████████████████████  99% (21 pods) c6in.xlarge/$0.227  Spot      - Ready 
                              memory ███████████████████████████████████  99%                                                 
ip-10-63-240-143.ec2.internal cpu    ██████████████████████████████████░  97% (14 pods) r6i.large/$0.126    Spot      - Ready 
                              memory █████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░  15%                                                 
ip-10-63-244-109.ec2.internal cpu    ██████████████████████████████████░  96% (20 pods) c6in.xlarge/$0.227  Spot      - Ready 
                              memory ██████████████████████████████████░  98%                                                 
ip-10-63-246-161.ec2.internal cpu    ███████████████████████████████████  99% (29 pods) r6id.2xlarge/$0.605 Spot      - Ready 
                              memory █████████░░░░░░░░░░░░░░░░░░░░░░░░░░  25%                                                 
ip-10-63-246-95.ec2.internal  cpu    ███████████████████████████░░░░░░░░  76% (13 pods) c6id.large/$0.101   Spot      - Ready 
                              memory ███████████████████░░░░░░░░░░░░░░░░  54%                                                 
```

For example the r6id.2xlarge should be more like $0.1608 per Hour

This was with the latest version installed with Go.

### PR DESCRIPTION
**Pull request by tzneal**
*Issue #, if available:*
Fixes  #63
*Description of changes:*

Treat spot price as unknown if we don't know it instead of falling back to the OD price.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by jonathan-innis — APPROVED** [review]
LGTM 🚀

**Comment by FernandoMiguel** [comment]
Under what circumstances is the spot price unknown ?

**Comment by tzneal** [comment]
If you display the pricing lookup.  We know the on-demand from the built-in prices, but don't have a static lookup table for spot prices.

**Comment by mballoni** [comment]
@tzneal apologies for the silly question but how do I display the pricing lookup?

**Comment by tzneal** [comment]
Typo on my part 😆  If you *disable* the pricing loop via `-disable-pricing`, then we won't know the spot or fargate pricing and won't display them.

**Comment by tzneal** [comment]
It sounds like it is unable to hit the EC2 spot pricing API.  Are any logs reported on startup?  They would clear pretty quickly as it draws the screen.

**Comment by mballoni** [comment]
No logs on startup on this latest version.
However I let it open here and noticed that new nodes are displaying the spot price, but not existing ones. Is this the expected behaviour?

**Comment by mballoni** [comment]
Thank you Todd, you rock!

**Pull request merged**
